# Data Cleaning

1. "Names"- changing this to a factor indicating has a name or no name. Some "Names" just have female/male, Dog, cat, or a number, I considered them as no name. 

2. Health-related variables: "Sterilized", "Dewormed", "Vaccinated", and "Health". I changed these from numerical to factor variables. I also renumbered not sterilized/dewormed/vaccinated as 0, and sterilized/dewromed/vaccinated as 1, and those with no information given as NA.
For "Health", 0 indicates healthy, 1 minor injury, and 2 severe injury when rescued.

3. "MixedBreed": This is a new variable that I created. If Breed1 is 307, then the animal is mixed breed.

4. "Description"- I changed this to "description length", indicating the number of words in the description.

5. "magnitude" and "score" are the two variables related to description sentiments. These are generated by Google's Natural Language API. I extracted these variables from the json files and added them to my data.
"Score" refers to how negative and positive the description is, -1 being the most negative, 1 being the most positive. "Magnitude" indicates the strength of the description.