# Ordered Logistic Regression
Have you ever wondered what to do when you want to predict more than 2 categories, and these categories seem to be ordered*? Ordered logistic regression is the way to go! 

## Proportional Odds Assumption
For ordered logistic regression, we assume that the relationship between each pair of outcome groups is the same. In other words, the coefficient for variable A will be the same regardless of whether it's describing the relationship between outcome group 1 and 2, or outcome group 2 and 3.  

## Interpretation
The interpretation for ordered logistic regression is very similar to logistic regression. 
Let Y be an ordinal outcome with J categories. $\beta_{j0}$s are the "cutpoints" between adjacent categories, often seen as the intercept. $\beta_i$s are the coefficients, and $x_i$s are prediction variables. 
Our logistic regression model would look something like this:
$$logit(P(Y\leq j))=\beta_{j0}+\beta_1x_1-...-\beta_nx_n$$
We will see a specific example of this in the next chapter. 

*In this case, we have 5 categories for adoption speed, and we believe that the "distance" between these 5 adoption speeds are not equal.
