<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 7 Modelling | STAT 454 Bayesian Statistics - Pet Adoption</title>
  <meta name="description" content="Chapter 7 Modelling | STAT 454 Bayesian Statistics - Pet Adoption" />
  <meta name="generator" content="bookdown 0.18.1 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 7 Modelling | STAT 454 Bayesian Statistics - Pet Adoption" />
  <meta property="og:type" content="book" />
  
  
  
  <meta name="github-repo" content="connie-zhang/pet-adoption" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 7 Modelling | STAT 454 Bayesian Statistics - Pet Adoption" />
  
  
  

<meta name="author" content="Connie Zhang, Spring 2020 Macalester College" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="ordered-logistic-regression.html"/>
<link rel="next" href="final-model.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Preface</a></li>
<li class="chapter" data-level="2" data-path="motivation.html"><a href="motivation.html"><i class="fa fa-check"></i><b>2</b> Motivation</a><ul>
<li class="chapter" data-level="2.1" data-path="motivation.html"><a href="motivation.html#why-this"><i class="fa fa-check"></i><b>2.1</b> Why this?</a></li>
<li class="chapter" data-level="2.2" data-path="motivation.html"><a href="motivation.html#a-snapshot"><i class="fa fa-check"></i><b>2.2</b> A snapshot</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-source.html"><a href="data-source.html"><i class="fa fa-check"></i><b>3</b> Data Source</a><ul>
<li class="chapter" data-level="3.1" data-path="data-source.html"><a href="data-source.html#variable-table"><i class="fa fa-check"></i><b>3.1</b> Variable Table</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="data-cleaning.html"><a href="data-cleaning.html"><i class="fa fa-check"></i><b>4</b> Data Cleaning</a></li>
<li class="chapter" data-level="5" data-path="visualizations.html"><a href="visualizations.html"><i class="fa fa-check"></i><b>5</b> Visualizations</a><ul>
<li class="chapter" data-level="5.1" data-path="visualizations.html"><a href="visualizations.html#general-impression"><i class="fa fa-check"></i><b>5.1</b> General Impression</a></li>
<li class="chapter" data-level="5.2" data-path="visualizations.html"><a href="visualizations.html#starting-off"><i class="fa fa-check"></i><b>5.2</b> Starting off</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="ordered-logistic-regression.html"><a href="ordered-logistic-regression.html"><i class="fa fa-check"></i><b>6</b> Ordered Logistic Regression</a><ul>
<li class="chapter" data-level="6.1" data-path="ordered-logistic-regression.html"><a href="ordered-logistic-regression.html#proportional-odds-assumption"><i class="fa fa-check"></i><b>6.1</b> Proportional Odds Assumption</a></li>
<li class="chapter" data-level="6.2" data-path="ordered-logistic-regression.html"><a href="ordered-logistic-regression.html#interpretation"><i class="fa fa-check"></i><b>6.2</b> Interpretation</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="modelling.html"><a href="modelling.html"><i class="fa fa-check"></i><b>7</b> Modelling</a><ul>
<li class="chapter" data-level="7.1" data-path="modelling.html"><a href="modelling.html#model-1"><i class="fa fa-check"></i><b>7.1</b> Model 1</a><ul>
<li class="chapter" data-level="7.1.1" data-path="modelling.html"><a href="modelling.html#posterior-inference"><i class="fa fa-check"></i><b>7.1.1</b> Posterior Inference</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="modelling.html"><a href="modelling.html#model-2"><i class="fa fa-check"></i><b>7.2</b> Model 2</a><ul>
<li class="chapter" data-level="7.2.1" data-path="modelling.html"><a href="modelling.html#model-building"><i class="fa fa-check"></i><b>7.2.1</b> Model Building</a></li>
<li class="chapter" data-level="7.2.2" data-path="modelling.html"><a href="modelling.html#posterior-inference-1"><i class="fa fa-check"></i><b>7.2.2</b> Posterior Inference</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="modelling.html"><a href="modelling.html#model-3"><i class="fa fa-check"></i><b>7.3</b> Model 3</a><ul>
<li class="chapter" data-level="7.3.1" data-path="modelling.html"><a href="modelling.html#model-building-1"><i class="fa fa-check"></i><b>7.3.1</b> Model Building</a></li>
<li class="chapter" data-level="7.3.2" data-path="modelling.html"><a href="modelling.html#posterior-inference-2"><i class="fa fa-check"></i><b>7.3.2</b> Posterior Inference</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="modelling.html"><a href="modelling.html#making-some-adjustments"><i class="fa fa-check"></i><b>7.4</b> Making some adjustments</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="final-model.html"><a href="final-model.html"><i class="fa fa-check"></i><b>8</b> Final Model</a><ul>
<li class="chapter" data-level="8.1" data-path="final-model.html"><a href="final-model.html#discussion"><i class="fa fa-check"></i><b>8.1</b> Discussion</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="shiny-apps.html"><a href="shiny-apps.html"><i class="fa fa-check"></i><b>9</b> Shiny Apps!</a><ul>
<li class="chapter" data-level="9.1" data-path="shiny-apps.html"><a href="shiny-apps.html#user-input"><i class="fa fa-check"></i><b>9.1</b> User Input</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="final-reflections.html"><a href="final-reflections.html"><i class="fa fa-check"></i><b>10</b> Final Reflections</a><ul>
<li class="chapter" data-level="10.1" data-path="final-reflections.html"><a href="final-reflections.html#advice-for-first-time-capstone-people"><i class="fa fa-check"></i><b>10.1</b> Advice for first time capstone people</a></li>
<li class="chapter" data-level="10.2" data-path="final-reflections.html"><a href="final-reflections.html#acknowledgements"><i class="fa fa-check"></i><b>10.2</b> Acknowledgements</a></li>
<li class="chapter" data-level="10.3" data-path="final-reflections.html"><a href="final-reflections.html#citations"><i class="fa fa-check"></i><b>10.3</b> Citations</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">STAT 454 Bayesian Statistics - Pet Adoption</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="modelling" class="section level1">
<h1><span class="header-section-number">Chapter 7</span> Modelling</h1>
<p>First, let’s load some essential package.</p>
<p>We will also create a sample of 1000 for faster modelling.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" title="1"><span class="kw">load</span>(<span class="st">&quot;adoption.RData&quot;</span>)</a>
<a class="sourceLine" id="cb1-2" title="2"><span class="kw">set.seed</span>(<span class="dv">454</span>)</a>
<a class="sourceLine" id="cb1-3" title="3">mysample &lt;-<span class="st"> </span>adoption[<span class="kw">sample</span>(<span class="dv">1</span><span class="op">:</span><span class="kw">nrow</span>(adoption), <span class="dv">1000</span>,</a>
<a class="sourceLine" id="cb1-4" title="4">   <span class="dt">replace=</span><span class="ot">FALSE</span>),]</a></code></pre></div>
<p>Below is the function I wrote to compute the accuracy of each model.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb2-1" title="1">ordinal_accuracy&lt;-<span class="cf">function</span>(post_preds,mydata){</a>
<a class="sourceLine" id="cb2-2" title="2">  post_preds&lt;-<span class="kw">as.data.frame</span>(post_preds)</a>
<a class="sourceLine" id="cb2-3" title="3">  results&lt;-<span class="kw">c</span>()</a>
<a class="sourceLine" id="cb2-4" title="4">  <span class="cf">for</span> (j <span class="cf">in</span> (<span class="dv">1</span><span class="op">:</span><span class="kw">length</span>(post_preds))){</a>
<a class="sourceLine" id="cb2-5" title="5">    results[j]&lt;-<span class="kw">as.numeric</span>(<span class="kw">tail</span>(<span class="kw">names</span>(<span class="kw">sort</span>(<span class="kw">table</span>(post_preds[,j]))))[<span class="dv">5</span>])</a>
<a class="sourceLine" id="cb2-6" title="6">    }</a>
<a class="sourceLine" id="cb2-7" title="7">  results&lt;-<span class="kw">as.data.frame</span>(results)</a>
<a class="sourceLine" id="cb2-8" title="8">  compare&lt;-<span class="kw">cbind</span>(results,mydata<span class="op">$</span>AdoptionSpeed)</a>
<a class="sourceLine" id="cb2-9" title="9">  compare&lt;-compare <span class="op">%&gt;%</span><span class="kw">mutate</span>(<span class="dt">results=</span><span class="kw">as.numeric</span>(results))</a>
<a class="sourceLine" id="cb2-10" title="10">  compare&lt;-compare <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="st">`</span><span class="dt">mydata$AdoptionSpeed</span><span class="st">`</span>=<span class="kw">as.numeric</span>(<span class="st">`</span><span class="dt">mydata$AdoptionSpeed</span><span class="st">`</span>))</a>
<a class="sourceLine" id="cb2-11" title="11">  compare&lt;-compare <span class="op">%&gt;%</span><span class="kw">mutate</span>(<span class="dt">accuracy=</span><span class="kw">ifelse</span>(<span class="kw">as.numeric</span>(results)<span class="op">==</span><span class="kw">as.numeric</span>(<span class="st">`</span><span class="dt">mydata$AdoptionSpeed</span><span class="st">`</span>),<span class="dv">1</span>,<span class="dv">0</span>))</a>
<a class="sourceLine" id="cb2-12" title="12">  <span class="kw">print</span>(<span class="kw">sum</span>(compare<span class="op">$</span>accuracy)<span class="op">/</span><span class="kw">length</span>(post_preds))</a>
<a class="sourceLine" id="cb2-13" title="13">}</a></code></pre></div>
<div id="model-1" class="section level2">
<h2><span class="header-section-number">7.1</span> Model 1</h2>
<p>From fig 1- fig n, we see that health factors and type can be useful factors in predicting adoption speed.
For this model, we have to set a R2 prior. I set R2 at 0.5 and what=NULL, which will give us a standard uniform prior on R2.
### Model Building
<span class="math display">\[
\text{Let }Y_i\text{ be the adoption speed with k=0,1,2,3,4.}
\\y_i|(\beta_{0k},\beta_1,...,\beta_6)\sim Bern(\theta_{ki})\text{ where }\theta_{ki}\text{ is the }P(Y_i\leq k)\text{ for the }i^{th}\text{ animal.}
\\log(\frac{\theta_{ki}}{1-\theta_{ki}})=logit(\hat P(Y\leq k))=\beta_{k0}+\beta_1x_1...+\beta_5x_5
\\\text{ where }x_i\text{ for i from 1 to 6 is the indicator for cat, minor injury, severe injury,}
\\\text{sterilization, vaccination, and dewormed.}
\\\beta_{k0}\sim N(m_{k0},s_{k0}^2)
\\\beta_1\sim N(m_1,s_1^2)
\\...\]</span></p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" title="1">model1 &lt;-<span class="st"> </span><span class="kw">stan_polr</span>(AdoptionSpeed <span class="op">~</span><span class="st"> </span>Type<span class="op">+</span>Health<span class="op">+</span>Sterilized<span class="op">+</span>Vaccinated<span class="op">+</span>Dewormed, <span class="dt">data =</span>mysample, <span class="dt">prior=</span><span class="kw">R2</span>(<span class="fl">0.5</span>,<span class="dt">what=</span><span class="ot">NULL</span>),<span class="dt">iter=</span><span class="dv">5000</span>, <span class="dt">seed =</span> <span class="dv">454</span>)</a></code></pre></div>
<div id="posterior-inference" class="section level3">
<h3><span class="header-section-number">7.1.1</span> Posterior Inference</h3>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4-1" title="1">model1_summary&lt;-<span class="kw">summary</span>(model1)</a>
<a class="sourceLine" id="cb4-2" title="2"><span class="kw">head</span>(<span class="kw">as.data.frame</span>(model1_summary), <span class="dv">-2</span>)</a></code></pre></div>
<pre><code>##                     mean         mcse          sd         10%          50%
## Type1       -0.291472332 1.067107e-03 0.128917172 -0.45490997 -0.291619825
## Health1      0.441523473 3.135560e-03 0.350471059 -0.01079189  0.437815394
## Health2      2.289862443 1.401822e-02 1.356098798  0.68125324  2.195511682
## Sterilized1  0.690688772 1.535365e-03 0.164162835  0.48092258  0.688819102
## Vaccinated1  0.318715747 1.655190e-03 0.179963272  0.08924947  0.318538724
## Dewormed1   -0.001789522 1.616438e-03 0.168594313 -0.21720001 -0.001004759
## 0|1         -3.355148548 2.201978e-03 0.232536209 -3.65773490 -3.349498499
## 1|2         -1.058289904 1.284121e-03 0.139953255 -1.23837624 -1.057180267
## 2|3          0.276656461 1.187258e-03 0.133952418  0.10538132  0.276139337
## 3|4          1.272267361 1.207162e-03 0.140589158  1.09125504  1.271952833
## mean_PPD:0   0.031505172 8.265987e-05 0.008632395  0.02093596  0.030788177
## mean_PPD:1   0.203957020 1.955397e-04 0.019572049  0.17980296  0.203201970
## mean_PPD:2   0.288257266 2.204405e-04 0.022416216  0.25985222  0.288177340
## mean_PPD:3   0.214343966 1.973403e-04 0.020048851  0.18965517  0.214285714
##                     90% n_eff      Rhat
## Type1       -0.12640415 14595 0.9999596
## Health1      0.89662335 12493 0.9997813
## Health2      4.02976553  9358 0.9999248
## Sterilized1  0.90384820 11432 1.0000488
## Vaccinated1  0.54993335 11821 0.9998534
## Dewormed1    0.21453193 10878 0.9998297
## 0|1         -3.06134550 11152 1.0000541
## 1|2         -0.87929294 11878 0.9998446
## 2|3          0.44947033 12729 1.0000083
## 3|4          1.45397384 13564 1.0001160
## mean_PPD:0   0.04310345 10906 0.9999094
## mean_PPD:1   0.23029557 10018 0.9999413
## mean_PPD:2   0.31650246 10341 1.0001028
## mean_PPD:3   0.24014778 10322 1.0000672</code></pre>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb6-1" title="1"><span class="kw">set.seed</span>(<span class="dv">454</span>)</a>
<a class="sourceLine" id="cb6-2" title="2">model_data1&lt;-mysample <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb6-3" title="3"><span class="st">  </span>dplyr<span class="op">::</span><span class="kw">select</span>(AdoptionSpeed, Type,Health,Sterilized,Vaccinated,Dewormed) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb6-4" title="4"><span class="st">  </span><span class="kw">na.omit</span>()</a>
<a class="sourceLine" id="cb6-5" title="5">my_prediction1 &lt;-<span class="st"> </span><span class="kw">posterior_predict</span>(</a>
<a class="sourceLine" id="cb6-6" title="6">  model1, </a>
<a class="sourceLine" id="cb6-7" title="7">  <span class="dt">newdata =</span> model_data1)</a>
<a class="sourceLine" id="cb6-8" title="8"></a>
<a class="sourceLine" id="cb6-9" title="9"><span class="kw">ordinal_accuracy</span>(my_prediction1,model_data1)</a></code></pre></div>
<pre><code>## [1] 0.2438424</code></pre>
<p>The formula using the posterior means of each variable is:
<span class="math display">\[logit(\hat P(Y\leq k))=\beta_{k0}-0.291*Type+0.442*Health1+2.290*Health2+0.691*Sterilized1
\\+0.319*Vaccinated1-0.002*Dewormed1
\\\text{For k =0,1,2,3,4}, \beta_{k0}=0,-3.62,-1.42,-0.17,0.76\text{ respectively}\]</span>
The accuracy for this model is 0.244.
If an animal has a severe injury, then the odds of that animal getting adopted slower will increase by e^2.290=9.87 times than a healthy animal, keeping all other variables constant.
We can see that the mean of Dewormed is near zero, therefore, we will exclude Dewormed in our future model.</p>
</div>
</div>
<div id="model-2" class="section level2">
<h2><span class="header-section-number">7.2</span> Model 2</h2>
<p>With further investigations, we have also found “AgeGroup” and “mix_breed” to be important factors. We will include these in our models.</p>
<div id="model-building" class="section level3">
<h3><span class="header-section-number">7.2.1</span> Model Building</h3>
<p><span class="math display">\[
\text{Let }Y_i\text{ be the adoption speed with k=0,1,2,3,4.}
\\y_i|(\beta_{0k},\beta_1,...,\beta_10)\sim Bern(\theta_{ki})\text{ where }\theta_{ki}\text{ is the }P(Y_i\leq k)\text{ for the }i^{th}\text{ animal.}
\\log(\frac{\theta_{ki}}{1-\theta_{ki}})=logit(\hat P(Y\leq k))=\beta_{k0}+\beta_1x_1...+\beta_{10}x_{10}
\\\text{ where }x_i\text{ for i from 1 to 11 is the indicator for cat, minor/severe injury,}
\\\text{sterilization, vaccination, age groups 1-5, and Mix breed.}
\\\beta_{k0}\sim N(m_{k0},s_{k0}^2)
\\\beta_1\sim N(m_1,s_1^2)
\\...\]</span></p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb8-1" title="1">model2 &lt;-<span class="st"> </span><span class="kw">stan_polr</span>(AdoptionSpeed <span class="op">~</span><span class="st"> </span>Type<span class="op">+</span>Health<span class="op">+</span>Sterilized<span class="op">+</span>Vaccinated<span class="op">+</span>AgeGroup<span class="op">+</span>MixedBreed, <span class="dt">data =</span>mysample, <span class="dt">prior=</span><span class="kw">R2</span>(<span class="fl">0.5</span>,<span class="dt">what=</span><span class="ot">NULL</span>),<span class="dt">iter=</span><span class="dv">5000</span>, <span class="dt">seed =</span> <span class="dv">454</span>)</a></code></pre></div>
</div>
<div id="posterior-inference-1" class="section level3">
<h3><span class="header-section-number">7.2.2</span> Posterior Inference</h3>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb9-1" title="1">model2_summary&lt;-<span class="st"> </span><span class="kw">summary</span>(model2)</a>
<a class="sourceLine" id="cb9-2" title="2"><span class="kw">head</span>(<span class="kw">as.data.frame</span>(model2_summary), <span class="dv">-2</span>)</a></code></pre></div>
<pre><code>##                    mean         mcse          sd         10%         50%
## Type1        0.48778366 1.707863e-03 0.221427458  0.19976369  0.48937164
## Health1      0.47969467 3.195916e-03 0.348317802  0.03818016  0.47965636
## Health2      1.67486939 1.220502e-02 1.279389983  0.13553622  1.58676636
## Sterilized1  0.47813952 1.457010e-03 0.181320803  0.24420605  0.47770227
## Vaccinated1  0.24826375 1.199002e-03 0.149064908  0.05697017  0.24762385
## AgeGroup1    0.54348134 1.459234e-03 0.170443602  0.32467603  0.54231742
## AgeGroup2    0.66716931 1.993412e-03 0.227959035  0.37680824  0.66989071
## AgeGroup3    0.96625893 3.180660e-03 0.345682844  0.51766283  0.95983629
## AgeGroup4    0.65239525 3.793133e-03 0.437359847  0.08932112  0.64813984
## AgeGroup5    0.53430605 5.266733e-03 0.592109782 -0.22336947  0.52774019
## MixedBreed1  1.06601710 2.044574e-03 0.228975968  0.77289049  1.06582076
## 0|1         -2.45032288 2.856396e-03 0.287372279 -2.81857404 -2.44775572
## 1|2         -0.13451482 2.159830e-03 0.230288981 -0.43149332 -0.13648189
## 2|3          1.23866701 2.011140e-03 0.232081787  0.93921284  1.23811248
## 3|4          2.26420168 2.033693e-03 0.241510274  1.95486028  2.26515793
## mean_PPD:0   0.03138345 7.841415e-05 0.008449069  0.02068127  0.03041363
## mean_PPD:1   0.20154197 1.840315e-04 0.019143089  0.17761557  0.20072993
## mean_PPD:2   0.28724696 2.128690e-04 0.022075926  0.25912409  0.28710462
## mean_PPD:3   0.21470985 1.891734e-04 0.019819265  0.18978102  0.21411192
##                     90% n_eff      Rhat
## Type1        0.76985933 16810 0.9998001
## Health1      0.92512579 11878 0.9998389
## Health2      3.31114337 10988 0.9999712
## Sterilized1  0.70659244 15487 0.9997555
## Vaccinated1  0.43924717 15457 0.9997827
## AgeGroup1    0.76354356 13643 1.0000624
## AgeGroup2    0.95776625 13077 0.9998310
## AgeGroup3    1.41472859 11812 0.9996562
## AgeGroup4    1.21477049 13295 0.9997109
## AgeGroup5    1.29127895 12639 0.9998504
## MixedBreed1  1.35920999 12542 0.9997835
## 0|1         -2.08201004 10122 0.9998176
## 1|2          0.16165719 11369 0.9997512
## 2|3          1.53309341 13317 0.9998544
## 3|4          2.57697695 14103 0.9998261
## mean_PPD:0   0.04257908 11610 0.9998802
## mean_PPD:1   0.22627737 10820 1.0000967
## mean_PPD:2   0.31630170 10755 0.9999731
## mean_PPD:3   0.23965937 10976 0.9998674</code></pre>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" title="1"><span class="kw">set.seed</span>(<span class="dv">454</span>)</a>
<a class="sourceLine" id="cb11-2" title="2">model_data2&lt;-mysample <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb11-3" title="3"><span class="st">  </span>dplyr<span class="op">::</span><span class="kw">select</span>(AdoptionSpeed, Type,Health,Sterilized,Vaccinated,AgeGroup,MixedBreed) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb11-4" title="4"><span class="st">  </span><span class="kw">na.omit</span>()</a>
<a class="sourceLine" id="cb11-5" title="5">my_prediction2 &lt;-<span class="st"> </span><span class="kw">posterior_predict</span>(</a>
<a class="sourceLine" id="cb11-6" title="6">  model2, </a>
<a class="sourceLine" id="cb11-7" title="7">  <span class="dt">newdata =</span> model_data2)</a>
<a class="sourceLine" id="cb11-8" title="8"></a>
<a class="sourceLine" id="cb11-9" title="9"><span class="kw">ordinal_accuracy</span>(my_prediction2,model_data2)</a></code></pre></div>
<pre><code>## [1] 0.2372263</code></pre>
<p>The model accuracy is something.
If an animal has a severe injury, then the odds of that animal getting adopted slower will increase by e^2.290=9.87 times than a healthy animal, keeping all other variables constant.
We can see that the mean of Dewormed is near zero, therefore, we will exclude Dewormed in our future model.
If an animal is in age group 1(4 to 11 months), then the odds of that animal getting adopted slower will increase by e^0.5=1.65 times than an animal that is in age group 0 (0 to 3 months), keeping all other variables constant. Similar situations apply to other age groups as well. From this, we can reasonably infer that animals in age group 0 are the most popular.
If an animal is a Mixed Breed, then the odds of that animal getting adopted slower will increase by e^1.1=3.00 times than an animal that is not mixed breed, keeping all other variables constant.</p>
</div>
</div>
<div id="model-3" class="section level2">
<h2><span class="header-section-number">7.3</span> Model 3</h2>
<p>In this model, we will be adding two interaction terms. The figure below shows that the younger the animal is, the less likely it will get sterilized, since the procedure can’t be done when they are young. Moreover, only dogs can be mixed breed. Therefore, we will add two interaction terms: Type<span class="math inline">\(*\)</span>MixedBreed and AgeGroup<span class="math inline">\(*\)</span>Sterilization.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb13-1" title="1"><span class="kw">set.seed</span>(<span class="dv">454</span>)</a>
<a class="sourceLine" id="cb13-2" title="2">mysample2 &lt;-<span class="st"> </span>adoption[<span class="kw">sample</span>(<span class="dv">1</span><span class="op">:</span><span class="kw">nrow</span>(adoption), <span class="dv">5000</span>,</a>
<a class="sourceLine" id="cb13-3" title="3">   <span class="dt">replace=</span><span class="ot">FALSE</span>),]</a></code></pre></div>
<div id="model-building-1" class="section level3">
<h3><span class="header-section-number">7.3.1</span> Model Building</h3>
<p><span class="math display">\[
\text{Let }Y_i\text{ be the adoption speed with k=0,1,2,3,4.}
\\y_i|(\beta_{0k},\beta_1,...,\beta_16)\sim Bern(\theta_{ki})\text{ where }\theta_{ki}\text{ is the }P(Y_i\leq k)\text{ for the }i^{th}\text{ animal.}
\\log(\frac{\theta_{ki}}{1-\theta_{ki}})=logit(\hat P(Y\leq k))=\beta_{k0}+\beta_1x_1...+\beta_{10}x_{10}+\beta_{11}x_1*x_10+\beta_{12}x_2*x_5+...+\beta_{16}x_2*x_9
\\\text{ where }x_i\text{ for i from 1 to 10 is the indicator for cat, minor/severe injury,}
\\\text{sterilization, vaccination, age groups 1-5, and Mix breed.}
\\\beta_{12}\text{ is the coefficient for the interaction term of Type*MixedBreed, and }\beta_{13}\text{ to }
\\\beta_{16}\text{ are the coefficients for the interaction terms of AgeGroup*Sterilization.}
\\\beta_{k0}\sim N(m_{k0},s_{k0}^2)
\\\beta_1\sim N(m_1,s_1^2)
\\...\]</span></p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb14-1" title="1">model3 &lt;-<span class="st"> </span><span class="kw">stan_polr</span>(AdoptionSpeed <span class="op">~</span><span class="st"> </span>Type<span class="op">*</span>MixedBreed<span class="op">+</span>Health<span class="op">+</span>Vaccinated<span class="op">+</span>AgeGroup<span class="op">*</span>Sterilized, <span class="dt">data=</span>mysample2, <span class="dt">prior=</span><span class="kw">R2</span>(<span class="fl">0.5</span>,<span class="dt">what=</span><span class="ot">NULL</span>),<span class="dt">iter=</span><span class="dv">5000</span>, <span class="dt">seed =</span> <span class="dv">454</span>)</a></code></pre></div>
</div>
<div id="posterior-inference-2" class="section level3">
<h3><span class="header-section-number">7.3.2</span> Posterior Inference</h3>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb15-1" title="1">model3_summary&lt;-<span class="st"> </span><span class="kw">summary</span>(model3)</a>
<a class="sourceLine" id="cb15-2" title="2"><span class="kw">head</span>(<span class="kw">as.data.frame</span>(model3_summary), <span class="dv">-2</span>)</a></code></pre></div>
<pre><code>##                              mean         mcse          sd         10%
## Type1                  0.47184938 7.571442e-04 0.099369735  0.34502111
## MixedBreed1            1.14663714 8.664970e-04 0.101586057  1.01709918
## Health1                0.05122540 1.800379e-03 0.186304253 -0.18641892
## Health2                0.80278228 7.639989e-03 0.791432469 -0.17825145
## Vaccinated1           -0.02398087 4.980604e-04 0.068539997 -0.11133954
## AgeGroup1              0.78827616 6.739903e-04 0.082801489  0.68306260
## AgeGroup2              0.99417754 1.215189e-03 0.140377451  0.81315639
## AgeGroup3              1.10500884 2.233080e-03 0.246135644  0.78769484
## AgeGroup4              0.40492872 3.234301e-03 0.342977893 -0.03423933
## AgeGroup5              0.47426010 3.940640e-03 0.439456830 -0.09357260
## Sterilized1            0.84939855 1.735068e-03 0.191216558  0.60522760
## Type1:MixedBreed1      9.60650467 2.003167e-01 8.358244119  0.67992165
## AgeGroup1:Sterilized1 -0.49303379 2.160991e-03 0.227324592 -0.78430283
## AgeGroup2:Sterilized1 -0.59788121 2.346639e-03 0.251455000 -0.92172987
## AgeGroup3:Sterilized1 -0.24281600 3.346378e-03 0.345010132 -0.68583759
## AgeGroup4:Sterilized1 -0.08827534 4.418418e-03 0.447682740 -0.65330275
## AgeGroup5:Sterilized1  0.18924715 5.880433e-03 0.591016385 -0.55840190
## 0|1                   -2.54365116 1.124570e-03 0.131534402 -2.71177567
## 1|2                   -0.11229020 8.622524e-04 0.102904006 -0.24379952
## 2|3                    1.19277358 8.301020e-04 0.103300534  1.06108647
## 3|4                    2.27586557 8.608239e-04 0.107812529  2.13864991
## mean_PPD:0             0.02865755 3.308651e-05 0.003629155  0.02405832
## mean_PPD:1             0.20931018 8.658040e-05 0.008713952  0.19805589
## mean_PPD:2             0.27400564 9.274487e-05 0.009704716  0.26172539
## mean_PPD:3             0.22778564 8.593592e-05 0.009222251  0.21603888
##                               50%         90% n_eff      Rhat
## Type1                  0.47091238  0.59933768 17225 0.9998226
## MixedBreed1            1.14689331  1.27840125 13745 1.0000647
## Health1                0.05300266  0.28981134 10708 1.0001129
## Health2                0.77418860  1.82183142 10731 1.0000717
## Vaccinated1           -0.02443910  0.06307548 18938 0.9997683
## AgeGroup1              0.78826905  0.89432167 15093 0.9999267
## AgeGroup2              0.99477645  1.17592832 13345 1.0001559
## AgeGroup3              1.10521743  1.42164234 12149 0.9999162
## AgeGroup4              0.40536116  0.84467658 11245 1.0003545
## AgeGroup5              0.48029323  1.03811684 12437 0.9996569
## Sterilized1            0.84696443  1.09515953 12146 0.9998550
## Type1:MixedBreed1      7.82300479 21.15974714  1741 1.0009795
## AgeGroup1:Sterilized1 -0.49095946 -0.20468675 11066 0.9998388
## AgeGroup2:Sterilized1 -0.60228281 -0.27214750 11482 1.0002522
## AgeGroup3:Sterilized1 -0.24425243  0.20395097 10630 0.9998063
## AgeGroup4:Sterilized1 -0.08286997  0.47721077 10266 1.0002454
## AgeGroup5:Sterilized1  0.18463079  0.94998265 10101 0.9998151
## 0|1                   -2.54213853 -2.37739940 13681 1.0000021
## 1|2                   -0.11187468  0.02045730 14243 0.9997855
## 2|3                    1.19304425  1.32506508 15486 0.9998167
## 3|4                    2.27509305  2.41527433 15686 0.9998125
## mean_PPD:0             0.02867558  0.03329283 12031 0.9999401
## mean_PPD:1             0.20923451  0.22041312 10130 0.9997596
## mean_PPD:2             0.27387606  0.28651276 10949 0.9997499
## mean_PPD:3             0.22770352  0.23961118 11517 0.9997480</code></pre>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb17-1" title="1"><span class="kw">set.seed</span>(<span class="dv">454</span>)</a>
<a class="sourceLine" id="cb17-2" title="2">model_data3&lt;-mysample2 <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb17-3" title="3"><span class="st">  </span>dplyr<span class="op">::</span><span class="kw">select</span>(AdoptionSpeed, Type,Health,Sterilized,Vaccinated,AgeGroup,MixedBreed) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb17-4" title="4"><span class="st">  </span><span class="kw">na.omit</span>()</a>
<a class="sourceLine" id="cb17-5" title="5">my_prediction3 &lt;-<span class="st"> </span><span class="kw">posterior_predict</span>(</a>
<a class="sourceLine" id="cb17-6" title="6">  model3,</a>
<a class="sourceLine" id="cb17-7" title="7">  <span class="dt">newdata =</span> model_data3)</a>
<a class="sourceLine" id="cb17-8" title="8"></a>
<a class="sourceLine" id="cb17-9" title="9"><span class="kw">ordinal_accuracy</span>(my_prediction3,model_data3)</a></code></pre></div>
<pre><code>## [1] 0.2038882</code></pre>
<p>The model accuracy is something.</p>
</div>
</div>
<div id="making-some-adjustments" class="section level2">
<h2><span class="header-section-number">7.4</span> Making some adjustments</h2>
<p>Our accuracy is less than ideal. One reason behind this could be due to how adoption speed is grouped. Group 0 is being adopted the day of, group 1 is being adopted between 2-7 days, and group 2 is being adopted between 8-30 days. The difference between group 0,1, and 2 can be due to chance, therefore, I’ve decided to group groups 0,1, and 2 into 1 group for our final model.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="ordered-logistic-regression.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="final-model.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
